site: seth0x41
title: Seth0x41
greetings: Hello there! 👋
description: >-
  Blogging about Software Engineering and Cyber Security.
lang: en-US
timezone: Africa/Cairo
data-theme: dark # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them
author:
  name: seth0x41
  bio: 🥱
  userpicture:
  username: seth0x41 # general username
  github: seth0x41 # github username
  twitter: seth0x41 # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: seth0x41 # linkedin profile
  email: Sec.MahmoudAlarby@email.com # email adress
  telegram: seth0x41
  reading: [" Spring in Action"]
# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://seth0x41.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  articles:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
